### PR TITLE
update some packages

### PR DESCRIPTION
**Pull request by z3ntu**
Changing a package:
- This package builds
- This PR adds a patch / This PR fixes formatting / This PR updates the package
- [x] I have regenerated `.SRCINFO` (`makepkg --printsrcinfo > .SRCINFO`)

### CODE REVIEW

**Comment by vanyasem** [comment]
thank you for your contribution! I will review this asap and update the packages on the server

**Comment by Austcool-Walker** [comment]
I got unity8 to launch to day on Manjaro Linux with the Nvidia Nonfree drivers!

**Comment by Austcool-Walker** [comment]
I used the changes that @z3ntu made :+1:

**Comment by vanyasem** [comment]
Wait, @Austcool-Walker , are you telling me that you got it to run on Nvidia Proprietary? You actually weren't supposed to be able to do so.. Could you share some screenshots?

**Comment by vanyasem** [comment]
Tested the PR - looks good to me, merged. Thank you !

**Pull request merged**
